apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ecobalyse-production
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/tfg-production/traceforgood/ecobalyse:#DOCKER_IMAGE_TAG#
        ports:
        - name: http1
          containerPort: 3000
        resources:
          limits:
            memory: 1024Mi
            cpu: 1000m
